Linear Algebra


In [2]:
import numpy as np

In [3]:
a=[]

In [4]:
for i in range(100):
    a.append(i)

In [5]:
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [6]:
type (a)

list

In [7]:
a=np.array(a)

In [8]:
type(a)

numpy.ndarray

In [9]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
b=np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [26]:
b[1:]

array([[2, 3, 4, 5, 6]])

In [11]:
b

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [12]:
b[1]

array([2, 3, 4, 5, 6])

In [13]:
b[1][2]

4

In [14]:
b.shape

(2, 5)

In [15]:
len(b)

2

In [16]:
len(b[0])

5

In [17]:
print? #explaination of that function

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [19]:
c=np.full((3,2),5)      #((row,column),fillvalue)
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [20]:
#identity matrix
np.eye?


Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [23]:
np.eye(4,dtype=int) #bydefault it returns float values

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [31]:
np.random.random_integers?


Docstring:
random_integers(low, high=None, size=None)

Random integers of type `np.int_` between `low` and `high`, inclusive.

Return random integers of type `np.int_` from the "discrete uniform"
distribution in the closed interval [`low`, `high`].  If `high` is
None (the default), then results are from [1, `low`]. The `np.int_`
type translates to the C long integer type and its precision
is platform dependent.

This function has been deprecated. Use randint instead.

.. deprecated:: 1.11.0

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is the *highest* such
    integer).
high : int, optional
    If provided, the largest (signed) integer to be drawn from the
    distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which

In [35]:

x=np.random.random((5,6))
x

array([[0.45101546, 0.38535389, 0.02235217, 0.95663816, 0.06565484,
        0.41974657],
       [0.85695025, 0.0276101 , 0.45624875, 0.77959326, 0.54407253,
        0.58760229],
       [0.29077213, 0.26596833, 0.46492556, 0.01843725, 0.08504918,
        0.25967361],
       [0.41274722, 0.49909756, 0.47889511, 0.83595074, 0.97531107,
        0.74106432],
       [0.40737689, 0.6052207 , 0.40294683, 0.65633207, 0.74525156,
        0.04707272]])

In [36]:
x[3:]   #after thhird row

array([[0.41274722, 0.49909756, 0.47889511, 0.83595074, 0.97531107,
        0.74106432],
       [0.40737689, 0.6052207 , 0.40294683, 0.65633207, 0.74525156,
        0.04707272]])

In [40]:
x[3:,:2]  #forth or fifth row ke first or second values

array([[0.41274722, 0.49909756],
       [0.40737689, 0.6052207 ]])

In [43]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [44]:
a+b

array([[ 6,  8],
       [10, 12]])

In [45]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [46]:
a*b

array([[ 5, 12],
       [21, 32]])

In [47]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [48]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [49]:
a@b

array([[19, 22],
       [43, 50]])

In [50]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [51]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [52]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [53]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [54]:
arr=np.array([[1,2,3],[4,5,6]])
flattened=arr.flatten()
flattened   #creates and return a copy in memory

array([1, 2, 3, 4, 5, 6])

In [55]:
ravel=arr.ravel()
ravel  #changes affect the original array

array([1, 2, 3, 4, 5, 6])

In [56]:
#stack

In [57]:
a=np.array([1,2,3,4,5])
b=np.array([9,8,7,6,5])


In [59]:
np.stack((a,b),axis=0),np.stack((a,b),axis=0).shape

(array([[1, 2, 3, 4, 5],
        [9, 8, 7, 6, 5]]),
 (2, 5))

In [64]:
y=np.stack((a,b),axis=1)

In [65]:
y


array([[1, 9],
       [2, 8],
       [3, 7],
       [4, 6],
       [5, 5]])

In [66]:
y.reshape(1,10)   

array([[1, 9, 2, 8, 3, 7, 4, 6, 5, 5]])

In [82]:
np.stack((a,b),axis=0),np.stack((a,b),axis=0).shape

(array([[1, 2, 3, 4, 5],
        [9, 8, 7, 6, 5]]),
 (2, 5))

In [84]:
np.min(x),np.max(x),np.average(x),np.mean(x),np.std(x)

(22, 90, 65.0, 65.0, 21.382235617446554)

In [73]:
choice=np.random.choice(x)
choice

76

In [75]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [81]:
np.ones((5,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [92]:
a=np.array([1,2,3,4,5])
b=np.array([9,8,7,6,5])
c=np.stack((a,b),axis=0)
c.shape

(2, 5)

In [91]:
np.expand_dims(c,axis=0).shape

(1, 2, 5)